/**
 * AIRiskAnalysis - AI-powered citation risk analysis component
 *
 * Displays an "Analyze with AI" button for cases with negative citation risk.
 * Uses Claude Sonnet 4.5 to provide detailed analysis of:
 * - Why the case is at risk
 * - Impact on legal theories
 * - Connection to citing cases
 * - Practical implications
 */
import React, { useState } from 'react';
import { aiAnalysisAPI } from '../lib/api';

interface AIRiskAnalysisProps {
  opinionId: number;
  caseName: string;
  severity: string;  // NEGATIVE, POSITIVE, NEUTRAL, UNKNOWN
  className?: string;
}

export const AIRiskAnalysis: React.FC<AIRiskAnalysisProps> = ({
  opinionId,
  caseName,
  severity,
  className = ''
}) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  // Only show for cases with negative citation risk
  if (severity !== 'NEGATIVE') {
    return null;
  }

  const handleAnalyze = async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await aiAnalysisAPI.analyzeRisk(opinionId);

      if (result.analysis) {
        setAnalysis(result.analysis);
        setExpanded(true);
      } else {
        setError('No analysis available');
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('Failed to analyze case risk');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={`bg-white rounded-lg border border-red-200 ${className}`}>
      {/* Header with button */}
      <div className="px-6 py-4 bg-red-50 rounded-t-lg border-b border-red-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-2xl">🤖</span>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">AI Risk Analysis</h3>
              <p className="text-sm text-gray-600">Powered by Claude Sonnet 4.5</p>
            </div>
          </div>

          {!analysis && (
            <button
              onClick={handleAnalyze}
              disabled={loading}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                loading
                  ? 'bg-gray-300 text-gray-600 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              {loading ? 'Analyzing...' : 'Analyze with AI'}
            </button>
          )}

          {analysis && (
            <button
              onClick={() => setExpanded(!expanded)}
              className="px-4 py-2 rounded-lg font-medium bg-gray-200 text-gray-700 hover:bg-gray-300 transition-colors"
            >
              {expanded ? 'Collapse' : 'Expand'} Analysis
            </button>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="px-6 py-4">
        {/* Loading state */}
        {loading && (
          <div className="flex items-center gap-3 py-8">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <div>
              <p className="text-gray-900 font-medium">Analyzing citation risk...</p>
              <p className="text-sm text-gray-600">This may take 10-30 seconds</p>
            </div>
          </div>
        )}

        {/* Error state */}
        {error && !loading && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4">
            <p className="text-red-800 font-medium">Error</p>
            <p className="text-sm text-red-700 mt-1">{error}</p>
            <button
              onClick={handleAnalyze}
              className="mt-3 text-sm text-red-700 hover:text-red-900 underline"
            >
              Try again
            </button>
          </div>
        )}

        {/* Analysis result */}
        {analysis && !loading && expanded && (
          <div className="prose prose-sm max-w-none">
            <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
              {analysis}
            </div>

            <div className="mt-6 pt-4 border-t border-gray-200 text-xs text-gray-500">
              <p>
                This analysis was generated by Claude Sonnet 4.5 based on the opinion text
                and negative citations. It should be used as a research aid and verified
                independently.
              </p>
            </div>
          </div>
        )}

        {/* Collapsed state */}
        {analysis && !loading && !expanded && (
          <div className="text-sm text-gray-600">
            <p>AI analysis available. Click "Expand Analysis" to view.</p>
          </div>
        )}

        {/* Initial state (no analysis yet) */}
        {!analysis && !loading && !error && (
          <div className="text-sm text-gray-600">
            <p className="mb-3">
              Get an AI-powered analysis of why <strong>{caseName}</strong> is at citation risk.
            </p>
            <ul className="list-disc list-inside space-y-1 text-gray-600">
              <li>Overview of the risk and what holdings are challenged</li>
              <li>Impact on legal theories and precedential value</li>
              <li>Connection to cases that cite it negatively</li>
              <li>Practical implications for legal professionals</li>
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

export default AIRiskAnalysis;
